# ci-cd.yml с двумя окружениями
name: CI/CD

on:
  push:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.14'

    - run: pip install -r requirements.txt pylint pytest
    - run: pylint animals/ --exit-zero
    - run: python manage.py migrate
    - run: pytest
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
    - uses: actions/checkout@v4
    - uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_STAGING_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    - uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.RENDER_PROD_ID }}
        api-key: ${{ secrets.RENDER_API_KEY }}